name: ci

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * 0' # weekly

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
                components: clippy, rustfmt
            - name: install dependencies
              run: |
                sudo apt-get install skopeo umoci capnproto
            - run: make lint check
            - name: publish
              if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
              run: |
                cargo publish -p puzzlefs-lib --token ${CRATES_TOKEN}
                cargo publish -p puzzlefs --token ${CRATES_TOKEN}
              env:
                CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
